-- AFSOO CRAFTS STUDIO - SUPABASE DATABASE SCHEMA SCRIPT
-- Copy and paste this script into your Supabase Dashboard -> SQL Editor and click RUN.

-- 1. Admins Table
CREATE TABLE IF NOT EXISTS public.admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  full_name TEXT DEFAULT 'Afsoo Administrator',
  role TEXT DEFAULT 'superadmin',
  avatar_url TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Default Superadmin Account
INSERT INTO public.admins (email, password, full_name, role)
VALUES ('afuzee0324@yahoo.com', 'Aafrinrawoof@20', 'Afsoo Administrator', 'superadmin')
ON CONFLICT (email) DO NOTHING;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  discount_price NUMERIC,
  stock INT DEFAULT 10,
  images TEXT[] DEFAULT ARRAY['/logo.png'],
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  category_name TEXT,
  is_featured BOOLEAN DEFAULT FALSE,
  is_bestseller BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone TEXT,
  password TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  shipping_address TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  pincode TEXT NOT NULL,
  subtotal NUMERIC NOT NULL,
  tax_amount NUMERIC DEFAULT 0,
  shipping_cost NUMERIC DEFAULT 0,
  total_amount NUMERIC NOT NULL,
  payment_method TEXT DEFAULT 'UPI_QR',
  payment_status TEXT DEFAULT 'PENDING',
  order_status TEXT DEFAULT 'PENDING',
  notes TEXT,
  items JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
  id INT PRIMARY KEY DEFAULT 1,
  store_name TEXT DEFAULT 'Afsoo Crafts Studio',
  store_logo TEXT DEFAULT '/logo.png',
  favicon TEXT DEFAULT '/logo.png',
  contact_number TEXT DEFAULT '+91 96292 17907',
  email TEXT DEFAULT 'support@afsoo.com',
  address TEXT DEFAULT 'Afsoo Design Studio, India',
  whatsapp TEXT DEFAULT '+91 96292 17907',
  instagram TEXT DEFAULT 'https://instagram.com/__afsoo__',
  currency TEXT DEFAULT 'INR',
  upi_qr_code TEXT DEFAULT '/upi_qr.png',
  upi_id TEXT DEFAULT 'zeeshan240896@oksbi',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Public Read Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow public insert to products" ON public.products FOR INSERT WITH CHECK (true);
